apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: routes
  namespace: tenant-b
spec:
  dependsOn:
    - name: workload
      namespace: vcluster-b
    - name: gateway-api
      namespace: flux-system
  targetNamespace: tenant-b
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-b/routes
  prune: true
  timeout: 5m
