apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workload
spec:
  kubeConfig:
    secretRef:
      name: vc-vcluster-b
      key: config
  targetNamespace: default
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-b/workload
  prune: true
  timeout: 5m
