apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster-platform
resources:
  - vcluster-platform_helmrelease.yaml
  - vcluster-platform_helmrepository.yaml
  - vcluster-platform_namespace.yaml
