apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: routes
  namespace: tenant-d
spec:
  dependsOn:
    - name: workload
      namespace: vcluster-d
    - name: gateway-api
      namespace: flux-system
  targetNamespace: tenant-d
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-d/routes
  prune: true
  timeout: 5m
