apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workload
  namespace: vcluster-d
spec:
  kubeConfig:
    secretRef:
      name: vc-vcluster-d
      key: config
  targetNamespace: default
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-d/workload
  prune: true
  timeout: 5m
