apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik
  namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      port: 8080
      protocol: HTTP
      hostname: "*.traefik.local"
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure
      port: 8443
      protocol: HTTPS
      hostname: "*.traefik.local"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: websecure-tls
            kind: Secret
            group: core