apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cilium
  prune: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/kube-prometheus-stack
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/metallb/config
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
   - name: kube-prometheus-stack
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cert-manager
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cert-manager/config
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/gateway-api
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
    - name: metallb-config
    - name: cert-manager
    - name: cert-manager-config
    - name: gateway-api
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/traefik
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-config
  namespace: flux-system
spec:
  dependsOn:
    - name: traefik
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/traefik/config
  prune: true
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: cilium
    - name: vcluster-a
    - name: vcluster-b
    - name: vcluster-c
    - name: vcluster-d
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/network-policies
  prune: true
  timeout: 5m