apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-b
  namespace: flux-system
spec:
  dependsOn:
    - name: vcluster-b
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenant/tenant-b
  prune: true