apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-d
  namespace: flux-system
spec:
  dependsOn:
    - name: vcluster-d
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenant/tenant-d
  prune: true
