apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenant-c
  namespace: flux-system
spec:
  dependsOn:
    - name: vcluster-c
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenant/tenant-c
  prune: true
