apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-d
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
    - name: metallb-config
    - name: gateway-api
    - name: traefik
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/vcluster-d
  prune: true
  timeout: 5m
