apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: routes
spec:
  dependsOn:
    - name: workload
    - name: gateway-api
      namespace: flux-system
  targetNamespace: tenant-a
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenant/tenant-a/routes
  prune: true
  timeout: 5m
